

services:
  mongodb:
    image: mongo:latest
    container_name: helpdesk-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=helpdesk
    networks:
      - helpdesk-network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: helpdesk-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/helpdesk
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - helpdesk-network
    volumes:
      - ./api:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  helpdesk-network:
    driver: bridge
